# Generated by Django 4.2.3 on 2023-08-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, default=2000)),
                ('description', models.TextField(default='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.PositiveSmallIntegerField(choices=[(0, 'Drama'), (1, 'Finance science'), (2, 'Horror'), (3, 'Fantasy'), (4, 'Criminal'), (5, 'Biography'), (6, 'History'), (7, 'Popularly scientific'), (8, 'Non-fiction'), (9, 'Law'), (10, 'Novel')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('biography', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='writers')),
                ('written_books', models.ManyToManyField(related_name='authors_written', related_query_name='author_written', to='booksapp.books')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField(blank=True, default='')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksapp.books')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(blank=True, default=5, null=True)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksapp.books')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(related_name='books_authored', related_query_name='book_authored', to='booksapp.writer'),
        ),
        migrations.AddField(
            model_name='books',
            name='genre_literary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booksapp.genre'),
        ),
    ]
