# Generated by Django 4.2.3 on 2023-08-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='written_books',
        ),
    ]
