# Generated by Django 4.2.3 on 2023-08-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_remove_writer_written_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='photo',
        ),
    ]
