# Generated by Django 4.2.3 on 2023-07-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_books_year_alter_books_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2000),
        ),
    ]
