# Generated by Django 4.2.3 on 2023-07-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0003_books_author_books_cover_books_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='cover',
            new_name='okładka',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='description',
            new_name='opis',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='year',
            new_name='rok',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='tytuł',
        ),
    ]
