# Generated by Django 4.2.3 on 2023-07-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0004_rename_author_books_autor_rename_cover_books_okładka_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='okładka',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='tytuł',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='rok',
            new_name='year',
        ),
    ]
