# Generated by Django 4.2.3 on 2023-07-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0005_rename_autor_books_author_rename_okładka_books_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='cover',
            new_name='okładka',
        ),
    ]
