# Generated by Django 4.2.3 on 2023-07-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0006_rename_cover_books_okładka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='description',
            new_name='opis',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='year',
            new_name='rok',
        ),
    ]
