# Generated by Django 4.2.3 on 2023-07-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0007_rename_description_books_opis_rename_year_books_rok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='title',
            new_name='tytuł',
        ),
    ]
