# Generated by Django 4.2.3 on 2023-07-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0008_rename_author_books_autor_rename_title_books_tytuł'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='okładka',
            field=models.ImageField(blank=True, null=True, upload_to='okładka'),
        ),
    ]
