# Generated by Django 4.2.3 on 2023-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0009_alter_books_okładka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='okładka',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
