# Generated by Django 4.2.3 on 2023-08-08 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0010_alter_books_okładka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(7, 'Popularno naukowe'), (5, 'Biografia'), (3, 'Fantazy'), (8, 'Literatura Faktu'), (4, 'Kryminał'), (1, 'Nauka o finansach'), (9, 'Prawo'), (2, 'Horror'), (0, 'Dramat'), (6, 'Historia')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='gatunek_literacki',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booksapp.genre'),
        ),
    ]
