# Generated by Django 4.2.3 on 2023-08-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0011_genre_books_gatunek_literacki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Horror'), (4, 'Kryminał'), (3, 'Fantazy'), (0, 'Dramat'), (6, 'Historia'), (8, 'Literatura Faktu'), (1, 'Nauka o finansach'), (7, 'Popularno naukowe'), (9, 'Prawo'), (5, 'Biografia')], default=0),
        ),
    ]
