# Generated by Django 4.2.3 on 2023-08-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0012_alter_genre_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(9, 'Prawo'), (7, 'Popularno naukowe'), (10, 'Powieść'), (3, 'Fantazy'), (6, 'Historia'), (5, 'Biografia'), (0, 'Dramat'), (4, 'Kryminał'), (1, 'Nauka o finansach'), (2, 'Horror'), (8, 'Literatura Faktu')], default=0),
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40)),
                ('nazwisko', models.CharField(max_length=40)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='writers')),
                ('książki', models.ManyToManyField(to='booksapp.books')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.PositiveSmallIntegerField(choices=[(3, 'dobra'), (4, 'Bardzo dobra'), (5, 'Wspaniała'), (2, ' zła'), (0, 'Nie da się czytać'), (1, 'bardzo zła')], default=5)),
                ('książka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksapp.books')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treść_recenzji', models.TextField(blank=True, default='')),
                ('książka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksapp.books')),
            ],
        ),
    ]
