# Generated by Django 4.2.3 on 2023-08-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0014_alter_genre_gatunek_alter_vote_ocena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='autor',
        ),
        migrations.AddField(
            model_name='books',
            name='autorzy',
            field=models.ManyToManyField(to='booksapp.writer'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(8, 'Literatura Faktu'), (0, 'Dramat'), (1, 'Nauka o finansach'), (10, 'Powieść'), (9, 'Prawo'), (3, 'Fantazy'), (2, 'Horror'), (6, 'Historia'), (5, 'Biografia'), (4, 'Kryminał'), (7, 'Popularno naukowe')], default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ocena',
            field=models.PositiveSmallIntegerField(choices=[(1, 'bardzo zła'), (3, 'dobra'), (4, 'Bardzo dobra'), (0, 'Nie da się czytać'), (5, 'Wspaniała'), (2, ' zła')], default=5),
        ),
    ]
