# Generated by Django 4.2.3 on 2023-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0015_remove_books_autor_books_autorzy_alter_genre_gatunek_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='książka',
            new_name='books',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='ocena',
        ),
        migrations.AddField(
            model_name='vote',
            name='gwiazdki',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='genre',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Powieść'), (4, 'Kryminał'), (9, 'Prawo'), (8, 'Literatura Faktu'), (0, 'Dramat'), (2, 'Horror'), (3, 'Fantazy'), (7, 'Popularno naukowe'), (6, 'Historia'), (1, 'Nauka o finansach'), (5, 'Biografia')], default=0),
        ),
    ]
