# Generated by Django 4.2.3 on 2023-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0016_rename_książka_vote_books_remove_vote_ocena_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Ocena',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='książka',
            new_name='books',
        ),
        migrations.AlterField(
            model_name='genre',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Kryminał'), (10, 'Powieść'), (9, 'Prawo'), (6, 'Historia'), (1, 'Nauka o finansach'), (3, 'Fantazy'), (2, 'Horror'), (0, 'Dramat'), (8, 'Literatura Faktu'), (7, 'Popularno naukowe'), (5, 'Biografia')], default=0),
        ),
    ]
