# Generated by Django 4.2.3 on 2023-08-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0018_alter_genre_gatunek_alter_ocena_gwiazdki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Kryminał'), (0, 'Dramat'), (5, 'Biografia'), (8, 'Literatura Faktu'), (6, 'Historia'), (10, 'Powieść'), (1, 'Nauka o finansach'), (7, 'Popularno naukowe'), (3, 'Fantazy'), (9, 'Prawo'), (2, 'Horror')], default=0),
        ),
    ]
