# Generated by Django 4.2.3 on 2023-08-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0019_alter_genre_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(7, 'Popularno naukowe'), (3, 'Fantazy'), (5, 'Biografia'), (4, 'Kryminał'), (10, 'Powieść'), (9, 'Prawo'), (1, 'Nauka o finansach'), (0, 'Dramat'), (6, 'Historia'), (8, 'Literatura Faktu'), (2, 'Horror')], default=0),
        ),
    ]
