# Generated by Django 4.2.3 on 2023-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0020_alter_genre_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Fantazy'), (9, 'Prawo'), (5, 'Biografia'), (10, 'Powieść'), (0, 'Dramat'), (7, 'Popularno naukowe'), (2, 'Horror'), (1, 'Nauka o finansach'), (4, 'Kryminał'), (6, 'Historia'), (8, 'Literatura Faktu')], default=0),
        ),
    ]
