# Generated by Django 4.2.3 on 2023-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0021_alter_genre_gatunek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='gatunek',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(9, 'Prawo'), (10, 'Powieść'), (8, 'Literatura Faktu'), (3, 'Fantazy'), (1, 'Nauka o finansach'), (7, 'Popularno naukowe'), (6, 'Historia'), (5, 'Biografia'), (2, 'Horror'), (0, 'Dramat'), (4, 'Kryminał')], default=0),
        ),
    ]
