# Generated by Django 4.2.3 on 2023-08-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0022_remove_genre_gatunek_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Historia'), (0, 'Dramat'), (2, 'Horror'), (9, 'Prawo'), (7, 'Popularno naukowe'), (10, 'Powieść'), (3, 'Fantazy'), (8, 'Literatura Faktu'), (4, 'Kryminał'), (5, 'Biografia'), (1, 'Nauka o finansach')], default=0),
        ),
    ]
