# Generated by Django 4.2.3 on 2023-08-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0023_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Biografia'), (10, 'Powieść'), (1, 'Nauka o finansach'), (4, 'Kryminał'), (3, 'Fantazy'), (8, 'Literatura Faktu'), (6, 'Historia'), (2, 'Horror'), (9, 'Prawo'), (0, 'Dramat'), (7, 'Popularno naukowe')], default=0),
        ),
    ]
