# Generated by Django 4.2.3 on 2023-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0025_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Horror'), (1, 'Nauka o finansach'), (10, 'Powieść'), (7, 'Popularno naukowe'), (3, 'Fantazy'), (8, 'Literatura Faktu'), (9, 'Prawo'), (0, 'Dramat'), (4, 'Kryminał'), (6, 'Historia'), (5, 'Biografia')], default=0),
        ),
    ]
