# Generated by Django 4.2.3 on 2023-08-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0026_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Powieść'), (7, 'Popularno naukowe'), (8, 'Literatura Faktu'), (6, 'Historia'), (9, 'Prawo'), (1, 'Nauka o finansach'), (3, 'Fantazy'), (2, 'Horror'), (0, 'Dramat'), (4, 'Kryminał'), (5, 'Biografia')], default=0),
        ),
    ]
