# Generated by Django 4.2.3 on 2023-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0027_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Historia'), (3, 'Fantazy'), (9, 'Prawo'), (7, 'Popularno naukowe'), (2, 'Horror'), (5, 'Biografia'), (4, 'Kryminał'), (8, 'Literatura Faktu'), (1, 'Nauka o finansach'), (10, 'Powieść'), (0, 'Dramat')], default=0),
        ),
    ]
